# Generated by Django 5.1.3 on 2025-04-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='role',
        ),
        migrations.AddField(
            model_name='roles',
            name='role',
            field=models.ManyToManyField(related_name='permission', to='auth.permission'),
        ),
    ]
