# Generated by Django 5.1.3 on 2025-04-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_permissions_role_roles_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='role',
            new_name='permission',
        ),
    ]
