# Generated by Django 5.1.3 on 2025-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_roles_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomize',
            name='roleID',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_customize', to='authentication.roles'),
        ),
    ]
