# Generated by Django 5.1.3 on 2025-04-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_usercustomize_roleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='permission',
        ),
        migrations.AddField(
            model_name='usercustomize',
            name='permission',
            field=models.ManyToManyField(related_name='permission', to='authentication.permissions'),
        ),
    ]
