# Generated by Django 5.1.3 on 2025-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0006_remove_roles_permission_usercustomize_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='permission',
            field=models.ManyToManyField(related_name='permission', to='auth.permission'),
        ),
    ]
