# Generated by Django 5.1.3 on 2025-04-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_roles_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='permission',
            field=models.ManyToManyField(related_name='permissions', to='authentication.permissions'),
        ),
    ]
