# Generated by Django 5.1.3 on 2025-04-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_roles_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='permission',
            field=models.ManyToManyField(related_name='permissions_role', to='authentication.permissions'),
        ),
        migrations.AlterField(
            model_name='usercustomize',
            name='permission',
            field=models.ManyToManyField(related_name='permission_user', to='authentication.permissions'),
        ),
    ]
