# Generated by Django 5.1.3 on 2025-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
