# Generated by Django 5.1.3 on 2025-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_roles_name'),
        ('configuracion', '0002_alter_menuitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_items', to='authentication.roles'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
