[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config", "libffi", "postgresql"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = ". /opt/venv/bin/activate && python manage.py migrate --noinput && gunicorn school_admin.wsgi:application --bind 0.0.0.0:${PORT}"
