# Generated by Django 5.1.3 on 2025-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_institucionacademica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucionacademica',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
