# Generated by Django 5.1.3 on 2025-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_institucionacademica_fecha_actualizacion'),
        ('sistema', '0007_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucionacademica',
            name='empresa',
            field=models.ManyToManyField(related_name='empresa', to='sistema.empresa'),
        ),
    ]
