# Generated by Django 5.1.3 on 2025-04-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_institucionacademica_empresa'),
        ('sistema', '0008_alter_tabsmodulo_modulo_alter_tabsmodulo_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucionacademica',
            name='empresa',
            field=models.ManyToManyField(related_name='institucion_academica', to='sistema.empresa'),
        ),
    ]
