# Generated by Django 5.1.3 on 2025-05-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_estadosrepublica_municipios'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipio', to='catalogos.estadosrepublica'),
        ),
    ]
