# Generated by Django 5.1.3 on 2025-05-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_municipios_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipios',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='municipios',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipios',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
