# Generated by Django 5.1.3 on 2025-05-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_rename_name_municipios_nombre_municipios_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipios',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='municipios',
            name='updated_at',
        ),
    ]
