# Generated by Django 5.1.3 on 2025-06-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_estatusmaestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclos',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodos',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
