# Generated by Django 5.1.3 on 2025-07-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_ciclos_estado_periodos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucionacademica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='instituciones/logos/'),
        ),
        migrations.AddField(
            model_name='institucionacademica',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
