# Generated by Django 5.1.3 on 2025-08-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_institucionacademica_logo_institucionacademica_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grado_grupos', to='catalogos.grados'),
        ),
    ]
