# Generated by Django 5.1.3 on 2025-09-07 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_alter_grupos_grado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institucionacademica',
            name='unidad_usuario',
            field=models.ManyToManyField(related_name='unidad_negocio', to=settings.AUTH_USER_MODEL),
        ),
    ]
