# Generated by Django 5.1.3 on 2025-11-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
