# Generated by Django 5.1.3 on 2025-04-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0003_modalidadesprograma_moduloeducativo_tipoprograma_and_more'),
        ('maestros', '0002_maestro_fecha_actualizacion_maestro_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaeducativo',
            name='maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='maestros.maestro'),
        ),
    ]
