# Generated by Django 5.1.3 on 2025-04-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0004_alter_programaeducativo_maestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariomodulo',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendariomodulo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moduloeducativo',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduloeducativo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='submodulo',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submodulo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoprograma',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoprograma',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
