# Generated by Django 5.1.3 on 2025-04-23 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_institucionacademica_empresa'),
        ('control_escolar', '0005_calendariomodulo_fecha_actualizacion_and_more'),
        ('maestros', '0003_alter_maestro_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciones',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestro_asignacion', to='maestros.maestro'),
        ),
        migrations.AlterField(
            model_name='calendariomodulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_modulo', to='control_escolar.moduloeducativo'),
        ),
        migrations.AlterField(
            model_name='enfoquepedagogico',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfoque_pedagogico', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_inscripcion', to='catalogos.ciclos'),
        ),
        migrations.AlterField(
            model_name='perfilingreso',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ingreso', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='programaeducativo',
            name='modalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='control_escolar.modalidadesprograma'),
        ),
        migrations.AlterField(
            model_name='publicoobjetivo',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publico_objetivo', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='requisitoegreso',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisito_egreso', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='requisitoingreso',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisito_ingreso', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='requisitopermanencia',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisito_permanencia', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='resultadoactualizacion',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_actualizacion', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='resultadoaplicacion',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_aplicacion', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='resultadocrecimiento',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_crecimiento', to='control_escolar.programaeducativo'),
        ),
    ]
