# Generated by Django 5.1.3 on 2025-06-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_estatusmaestro'),
        ('control_escolar', '0007_perfilegreso_orden_perfilingreso_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaeducativo',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programa_educativo', to='catalogos.ciclos'),
        ),
        migrations.AddField(
            model_name='programaeducativo',
            name='impartido_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programa_educativo', to='catalogos.periodos'),
        ),
    ]
