# Generated by Django 5.1.3 on 2025-06-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0008_programaeducativo_ciclo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaeducativo',
            name='ciclo',
        ),
    ]
