# Generated by Django 5.1.3 on 2025-06-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0009_remove_programaeducativo_ciclo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programaeducativo',
            old_name='impartido_en',
            new_name='periodo_imparticion',
        ),
    ]
