# Generated by Django 5.1.3 on 2025-07-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_institucionacademica_logo_institucionacademica_slug'),
        ('control_escolar', '0011_tipoevento_evento'),
        ('estudiantes', '0010_alter_estudiante_grupo_alter_estudiante_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaeducativo',
            name='inscripcion',
            field=models.ManyToManyField(blank=True, null=True, related_name='program', to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_inscripcion', to='catalogos.ciclos'),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_inscripcion', to='catalogos.grupos'),
        ),
    ]
