# Generated by Django 5.1.3 on 2025-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0012_programaeducativo_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodulo',
            name='path_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
