# Generated by Django 5.1.3 on 2025-08-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0013_submodulo_path_class'),
        ('maestros', '0006_maestro_estado_maestro_estatus_maestro_municipio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaeducativo',
            name='maestro',
        ),
        migrations.AddField(
            model_name='programaeducativo',
            name='maestro',
            field=models.ManyToManyField(blank=True, null=True, related_name='programas', to='maestros.maestro'),
        ),
    ]
