# Generated by Django 5.1.3 on 2025-09-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0015_typefile_materialmodulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmodulos',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='control_escolar.programaeducativo'),
        ),
    ]
