# Generated by Django 5.1.3 on 2025-10-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0017_baseprograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaeducativo',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
