# Generated by Django 5.1.3 on 2025-10-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0018_programaeducativo_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaeducativo',
            name='banner_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
