# Generated by Django 5.1.3 on 2025-11-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0021_remove_inscripcion_costo_pagado_tipopago_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaeducativo',
            name='duracion_meses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
