# Generated by Django 5.1.3 on 2025-11-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0022_programaeducativo_duracion_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaeducativo',
            name='costo_documentacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
