# Generated by Django 5.1.3 on 2025-11-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0023_programaeducativo_costo_documentacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripciones',
        ),
    ]
