# Generated by Django 5.1.3 on 2025-11-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0024_delete_inscripciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='concepto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
