# Generated by Django 5.1.3 on 2025-11-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_metodopago'),
        ('control_escolar', '0025_pago_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago', to='catalogos.metodopago'),
        ),
    ]
