# Generated by Django 5.1.3 on 2025-11-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0026_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
    ]
