# Generated by Django 5.1.3 on 2025-11-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0028_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='control_escolar.tipopago'),
        ),
    ]
