# Generated by Django 5.1.3 on 2025-11-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0029_alter_pago_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
