# Generated by Django 5.1.3 on 2025-11-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0030_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('excedente', 'Excedente'), ('parcial', 'Parcial'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
