# Generated by Django 5.1.3 on 2025-11-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0031_alter_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='costo_documentacion_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='costo_inscripcion_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio acordado con el asesor para esta inscripción específica', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='costo_mensualidad_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='notas_precio_custom',
            field=models.TextField(blank=True, help_text='Razón del precio personalizado (promoción, beca, acuerdo especial)', null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='tiene_precio_custom',
            field=models.BooleanField(default=False, help_text='Indica si esta inscripción tiene precios personalizados'),
        ),
    ]
