# Generated by Django 5.1.3 on 2026-01-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0032_inscripcion_costo_documentacion_acordado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
