# Generated by Django 5.1.3 on 2026-01-29 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0034_fichas_comisiones'),
        ('estudiantes', '0015_estudiante_telefono_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichas',
            name='perfil_estudiante',
        ),
        migrations.AddField(
            model_name='fichas',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='estudiantes.estudiante'),
        ),
    ]
