# Generated by Django 5.1.3 on 2026-01-30 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0035_remove_fichas_perfil_estudiante_fichas_estudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichas',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichas',
            name='autorizado_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizado_fichas', to=settings.AUTH_USER_MODEL),
        ),
    ]
