# Generated by Django 5.1.3 on 2025-04-05 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=100)),
                ('apellidoM', models.CharField(max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.genero')),
                ('nivEdu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.niveleducativo')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
