# Generated by Django 5.1.3 on 2025-04-05 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidad', to='catalogos.especialidades')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maestro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
