# Generated by Django 5.1.3 on 2025-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
    ]
