# Generated by Django 5.1.3 on 2025-05-14 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_institucionacademica_empresa'),
        ('maestros', '0003_alter_maestro_especialidad'),
        ('perfil', '0002_rename_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestro',
            old_name='numero_empleado',
            new_name='numero_colaborador',
        ),
        migrations.AddField(
            model_name='maestro',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestro', to='perfil.user'),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maestro_especialidad', to='catalogos.especialidades'),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestro', to=settings.AUTH_USER_MODEL),
        ),
    ]
