# Generated by Django 5.1.3 on 2025-05-18 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_rename_numero_empleado_maestro_numero_colaborador_and_more'),
        ('perfil', '0002_rename_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maestro', to='perfil.user'),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maestro', to=settings.AUTH_USER_MODEL),
        ),
    ]
