# Generated by Django 5.1.3 on 2025-05-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_estatusmaestro'),
        ('maestros', '0005_alter_maestro_perfil_alter_maestro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestro', to='catalogos.estadosrepublica'),
        ),
        migrations.AddField(
            model_name='maestro',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestro', to='catalogos.estatusmaestro'),
        ),
        migrations.AddField(
            model_name='maestro',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestro', to='catalogos.municipios'),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.especialidades'),
        ),
    ]
