# Generated by Django 5.1.3 on 2025-03-14 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educationalProgram', to='cursos.educationalprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('modulos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educationalProgram', to='cursos.modulos')),
            ],
        ),
    ]
