# Generated by Django 5.1.3 on 2025-10-10 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('unidad', models.CharField(choices=[('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses'), ('years', 'Años')], default='months', max_length=10)),
                ('intervalo', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('costo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descuento_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dias_entrega', models.PositiveBigIntegerField(default=3)),
                ('estado', models.IntegerField(default=0)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_pagos', models.PositiveIntegerField(default=1)),
                ('monto_por_periodo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('incluye_factura', models.IntegerField(default=0)),
                ('activo', models.IntegerField(default=0)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL)),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='invitaPro.periodicidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='invitaPro.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('requiere_produccion', models.IntegerField(default=0)),
                ('incluye_hosting', models.IntegerField(default=0)),
                ('es_recurrente', models.IntegerField(default=0)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='invitaPro.tipoproducto'),
        ),
    ]
