# Generated by Django 5.1.3 on 2025-11-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitaPro', '0002_periodicidad_owner_planpago_owner_producto_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='tipo_evento',
            new_name='tipo_producto',
        ),
    ]
