# Generated by Django 5.1.3 on 2025-11-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaPro', '0003_rename_tipo_evento_evento_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='include_password',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
