# Generated by Django 5.1.3 on 2025-11-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaPro', '0004_evento_include_password_evento_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='include_password',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='password',
        ),
        migrations.AddField(
            model_name='itinerariopaso',
            name='include_password',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itinerariopaso',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
