# Generated by Django 5.1.3 on 2025-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaPro', '0005_remove_evento_include_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerariopaso',
            name='url_map',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
