# Generated by Django 5.1.3 on 2025-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaPro', '0006_itinerariopaso_url_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerariopaso',
            name='url_map',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
