# Generated by Django 5.1.3 on 2025-11-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaPro', '0007_alter_itinerariopaso_url_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerariopaso',
            name='password_match',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
