# Generated by Django 5.1.3 on 2025-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaPro', '0008_itinerariopaso_password_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerariopaso',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
