# Generated by Django 5.1.3 on 2025-04-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('bgColor', models.CharField(max_length=20)),
                ('textColor', models.CharField(max_length=20)),
                ('route', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.ManyToManyField(blank=True, null=True, related_name='menu_items', to='authentication.roles')),
            ],
        ),
    ]
