# Generated by Django 5.1.3 on 2025-04-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('sistema', '0003_tabsmodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabsmodulo',
            name='permiso',
            field=models.ManyToManyField(to='authentication.permissions'),
        ),
    ]
