# Generated by Django 5.1.3 on 2025-04-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('sistema', '0004_tabsmodulo_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabsmodulo',
            name='permiso',
            field=models.ManyToManyField(related_name='permiso', to='authentication.permissions'),
        ),
    ]
