# Generated by Django 5.1.3 on 2025-04-14 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_roles_permission_usercustomize_permission'),
        ('sistema', '0005_alter_tabsmodulo_permiso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='usuario',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_menu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_role', to='authentication.roles'),
        ),
        migrations.CreateModel(
            name='AsignacionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.modulos')),
                ('otorgado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
