# Generated by Django 5.1.3 on 2025-04-23 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_roles_permission_and_more'),
        ('sistema', '0007_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabsmodulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pestanias', to='sistema.modulos'),
        ),
        migrations.AlterField(
            model_name='tabsmodulo',
            name='permiso',
            field=models.ManyToManyField(related_name='permiso_pestanias', to='authentication.permissions'),
        ),
    ]
