# Generated by Django 5.1.3 on 2025-04-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_tabsmodulo_modulo_alter_tabsmodulo_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabsmodulo',
            name='href',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabsmodulo',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
