# Generated by Django 5.1.3 on 2025-04-23 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_tabsmodulo_href_tabsmodulo_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tabsmodulo',
            name='user',
            field=models.ManyToManyField(related_name='pestanias', to=settings.AUTH_USER_MODEL),
        ),
    ]
