# Generated by Django 5.1.3 on 2025-06-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_tabsmodulo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
