# Generated by Django 5.1.3 on 2025-06-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_modulos_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabsmodulo',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
