# Generated by Django 5.1.3 on 2025-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_roles_permission_and_more'),
        ('sistema', '0013_empresa_logo_empresa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabsmodulo',
            name='permiso',
        ),
        migrations.AddField(
            model_name='tabsmodulo',
            name='rol',
            field=models.ManyToManyField(related_name='pestanias', to='authentication.roles'),
        ),
    ]
