from .genero import GeneroSerializer
from .nivel_educativo import NivelEducativoSerializer
from .tipo_nivel import TipoNivelSerializer
from .institucion_serializers import InstitucionAcademicaSerializer