# Generated by Django 5.1.3 on 2025-04-05 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('tutor_nombre', models.CharField(blank=True, max_length=100)),
                ('tutor_telefono', models.CharField(blank=True, max_length=15)),
                ('activo', models.IntegerField()),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.grupos')),
                ('nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.niveleducativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
