# Generated by Django 5.1.3 on 2025-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tutor_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tutor_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
