# Generated by Django 5.1.3 on 2025-05-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_estudiante_email_estudiante_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
