# Generated by Django 5.1.3 on 2025-05-16 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_estadosrepublica_municipios'),
        ('estudiantes', '0005_alter_estudiante_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to='catalogos.municipios'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to='catalogos.estadosrepublica'),
        ),
    ]
