# Generated by Django 5.1.3 on 2025-05-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_estudiante_municipio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
    ]
