# Generated by Django 5.1.3 on 2025-05-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_remove_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='nivel_educativo',
        ),
    ]
