# Generated by Django 5.1.3 on 2025-05-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_remove_municipios_created_at_and_more'),
        ('estudiantes', '0009_remove_estudiante_telefono'),
        ('perfil', '0002_rename_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.grupos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='perfil.user'),
        ),
    ]
