# Generated by Django 5.1.3 on 2025-08-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0010_alter_estudiante_grupo_alter_estudiante_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
