# Generated by Django 5.1.3 on 2025-08-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_estudiante_especialidad_estudiante_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
