# Generated by Django 5.1.3 on 2025-09-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_alter_estudiante_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
    ]
