# Generated by Django 5.1.3 on 2026-01-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_remove_estudiante_email_remove_estudiante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
