# Generated by Django 5.1.3 on 2026-01-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_estudiante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='telefono_adicional',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
