# Generated by Django 5.1.3 on 2025-04-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_institucionacademica_empresa'),
        ('crm', '0003_pipline_etapas_pipline'),
        ('sistema', '0007_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnidadNegocio',
        ),
        migrations.AddField(
            model_name='lead',
            name='tiempo_primera_respuesta',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipline',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_pipline', to='sistema.empresa'),
        ),
        migrations.AddField(
            model_name='pipline',
            name='unidad_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_academica', to='catalogos.institucionacademica'),
        ),
    ]
