# Generated by Django 5.1.3 on 2025-04-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0004_alter_programaeducativo_maestro'),
        ('crm', '0006_estadocita_tipocita_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interesado_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='control_escolar.programaeducativo'),
        ),
    ]
