# Generated by Django 5.1.3 on 2025-04-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0005_calendariomodulo_fecha_actualizacion_and_more'),
        ('crm', '0007_alter_lead_interesado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipline',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_escolar.programaeducativo'),
        ),
    ]
