# Generated by Django 5.1.3 on 2025-04-23 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_institucionacademica_empresa'),
        ('control_escolar', '0006_alter_asignaciones_profesor_and_more'),
        ('crm', '0008_pipline_programa'),
        ('sistema', '0008_alter_tabsmodulo_modulo_alter_tabsmodulo_permiso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='descripcion',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='nombre',
        ),
        migrations.AddField(
            model_name='lead',
            name='etapa_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_previos', to='crm.etapas'),
        ),
        migrations.AddField(
            model_name='notas',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='notas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='texto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_estado', to='crm.estadocita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agendadas_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='crm.tipocita'),
        ),
        migrations.AlterField(
            model_name='etapas',
            name='pipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='crm.pipline'),
        ),
        migrations.AlterField(
            model_name='historialleadinstitucion',
            name='cambiado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_lead_inst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialleadinstitucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_lead_inst', to='catalogos.institucionacademica'),
        ),
        migrations.AlterField(
            model_name='historialleadinstitucion',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_lead_inst', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_estatus', to='crm.estatus'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_etapa', to='crm.etapas'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.fuentes'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='interesado_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_interesado', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='pipline',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipline', to='sistema.empresa'),
        ),
        migrations.AlterField(
            model_name='pipline',
            name='unidad_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ua_pipline', to='catalogos.institucionacademica'),
        ),
    ]
