# Generated by Django 5.1.3 on 2025-04-25 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rename_descripcion_notas_texto_remove_lead_notas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activa', models.IntegerField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='crm.fuentes')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='campania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.campania'),
        ),
    ]
