# Generated by Django 5.1.3 on 2025-05-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_campania_lead_campania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
