# Generated by Django 5.1.3 on 2025-05-02 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0006_alter_asignaciones_profesor_and_more'),
        ('crm', '0012_remove_campania_fuente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campania',
            name='presupuesto',
        ),
        migrations.CreateModel(
            name='CampaniaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_campania', to='crm.campania')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campania_programa', to='control_escolar.programaeducativo')),
            ],
        ),
    ]
