# Generated by Django 5.1.3 on 2025-05-02 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_campania_presupuesto_campaniaprograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='campania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.campaniaprograma'),
        ),
    ]
