# Generated by Django 5.1.3 on 2025-05-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0006_alter_asignaciones_profesor_and_more'),
        ('crm', '0014_alter_lead_campania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interesado_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_interesado', to='control_escolar.programaeducativo'),
        ),
    ]
