# Generated by Django 5.1.3 on 2025-05-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_lead_interesado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='campania',
        ),
    ]
