# Generated by Django 5.1.3 on 2025-05-02 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_lead_campania'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.campaniaprograma'),
        ),
    ]
