# Generated by Django 5.1.3 on 2025-06-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_lead_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
