# Generated by Django 5.1.3 on 2025-06-11 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_estatusmaestro'),
        ('crm', '0019_alter_etapas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaniaprograma',
            name='unidad_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanias_unidad', to='catalogos.institucionacademica'),
        ),
        migrations.AddField(
            model_name='estatus',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estatus', to='crm.pipline'),
        ),
    ]
