# Generated by Django 5.1.3 on 2025-10-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_request'),
        ('invitaPro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='producto_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitaPro.producto'),
        ),
        migrations.AddField(
            model_name='request',
            name='producto_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_producto', to='invitaPro.producto'),
        ),
    ]
