# Generated by Django 5.1.3 on 2025-10-10 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_lead_producto_interes_request_producto_interes'),
        ('sistema', '0014_remove_tabsmodulo_permiso_tabsmodulo_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_empresa_related', to='sistema.empresa'),
        ),
        migrations.AddField(
            model_name='country',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_empresa_related', to='sistema.empresa'),
        ),
    ]
