# Generated by Django 5.1.3 on 2025-10-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_city_empresa_country_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='country',
            name='empresa',
        ),
    ]
