# Generated by Django 5.1.3 on 2025-10-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_remove_city_empresa_remove_country_empresa'),
        ('sistema', '0014_remove_tabsmodulo_permiso_tabsmodulo_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuentes',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes_crm', to='sistema.empresa'),
        ),
    ]
