# Generated by Django 5.1.3 on 2025-10-13 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0015_institucionacademica_unidad_usuario'),
        ('crm', '0028_alter_lead_producto_interes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.institucionacademica'),
        ),
    ]
