# Generated by Django 5.1.3 on 2025-10-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_request_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tiempo_primera_respuesta',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
