# Generated by Django 5.1.3 on 2025-10-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_request_tiempo_primera_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campania',
            name='activa',
        ),
        migrations.AddField(
            model_name='campania',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
