# Generated by Django 5.1.3 on 2025-10-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_campania_owner_campaniaprograma_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campania',
            old_name='owner',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='campaniaprograma',
            old_name='owner',
            new_name='usuario_id',
        ),
    ]
