# Generated by Django 5.1.3 on 2025-10-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_rename_owner_campania_usuario_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campania',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='campaniaprograma',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
