# Generated by Django 5.1.3 on 2025-04-23 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_institucionacademica_empresa'),
        ('estudiantes', '0002_estudiante_fecha_actualizacion_and_more'),
        ('examenes', '0002_alter_calificacionesexamen_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionesexamen',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_examen_calificacion', to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacionesexamen',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_calificacion', to='examenes.examenes'),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_examen', to='catalogos.materias'),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodo_examen', to='catalogos.periodos'),
        ),
        migrations.AlterField(
            model_name='examenes',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='examenes.tiposexamen'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_examen', to='examenes.examenes'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='examenes.tipopreguntas'),
        ),
        migrations.AlterField(
            model_name='respuestasestudiantes',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_estudiante', to='examenes.preguntas'),
        ),
    ]
