# Generated by Django 5.1.3 on 2025-10-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_comentario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceclase',
            name='password_platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
