# Generated by Django 5.1.3 on 2025-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_enlaceclase_password_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enlaceclase',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plataformasimparticion',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
