# Generated by Django 5.1.3 on 2025-10-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar', '0017_baseprograma'),
        ('plataforma', '0004_alter_comentario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='diplomado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='control_escolar.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='control_escolar.moduloeducativo'),
        ),
    ]
