from .categorias import Categoria
from .genero import Genero
from .ciclos import Ciclos
from .especialidades import Especialidades
from .especificaciones import Especification
from .grados import Grados
from .grupos import Grupos
from .materias import Materias
from .niveleducativo import NivelEducativo
from .subcategorias import SubCategoria
from .tipo_nivel import TipoNivel
from .niveles import Niveles
from .periodos import Periodos
from .instituciones_academicas import InstitucionAcademica
from .estados_republica import EstadosRepublica
from .municipios import Municipios